server:
  port: 9090
  servlet:
    context-path: /assignement
  #Show all queries
spring:
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  properties:
    hibernate:
      format_sql: true
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    org:
      hibernate:
        type: trace