server:
  port: 9090
  servlet:
    context-path: /assignement
  #Show all queries
spring:
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    org:
      hibernate:
        type: trace